environment:
  PYTHON: "C:\\Python27"
  SYSL_PLANTUML: http://www.plantuml.com/plantuml
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  GOPATH: c:\gopath

init:
  - git config --global core.autocrlf input
  - go env

clone_folder: c:\gopath\src\github.com\anz-bank\sysl

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%JAVA_HOME%\bin;%PATH%
  - pip install --upgrade setuptools
  - pip install py2exe_py2
  - pip install protobuf==3.5.1 # protobuf 3.5.2 and py2exe don't work together
  - pip install flake8==3.5.0
  - pip install . pytest
  - pip freeze
  - choco install gradle
  - go get -t -v github.com/anz-bank/sysl/sysl2/sysl

build: off

build_script:
  - go build -o dist/gosysl.exe github.com/anz-bank/sysl/sysl2/sysl

test_script:
  - flake8
  - pytest
  - pytest test/e2e --syslexe=sysl --reljamexe=reljam
  - gradle --no-daemon -b test\java\build.gradle test
  - go test -coverprofile=coverage.txt -covermode=atomic github.com/anz-bank/sysl/sysl2/sysl
  - test-gosysl.bat

after_test:
  - ps: Start-FileDownload 'http://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi' C:\VCForPython27.msi; echo "Done"
  - msiexec /i C:\VCForPython27.msi /quiet /q
  - XCOPY src\libs\google-site-packages-override\__init__.py  C:\Python27\Lib\site-packages\google /Y
  - python setup.py py2exe
  - pytest test/e2e --syslexe=dist/sysl.exe --reljamexe=dist/reljam.exe

artifacts:
  - path: 'dist'
    name: sysl-bundle-windows
    type: zip

deploy:
    provider: GitHub
    release: Sysl $(APPVEYOR_REPO_TAG_NAME)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    draft: true
    prerelease: true
    repository: anz-bank/sysl
    auth_token:
      secure: McTebLt7DvyCd7qa9oHl5DwPZeNHf7NdtSCtNBZre59iWCmC0T0HT+/yiHLDQMtk
    on:
      appveyor_repo_tag: true

