swagger: "2.0"
info:
  title: Simple
  description: Simple demo for swagger file import
paths:
  /test:
    get:
      description: Endpoint for testing GET
      responses:
        200:
          description: 200 OK
          schema:
            $ref: "#/definitions/SimpleObj"
definitions:
  SimpleObj:
    type: object
    properties:
      name:
        type: string
