info:
  description: |
    foo
  title: foo
  version: 0.0.0
paths:
  /testDots:
    get:
      consumes:
      - application/json
      description: No description.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: No description.
  /testResponseCodeEmpty:
    get:
      consumes:
      - application/json
      description: No description.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: No description.
  /testResponseCodeResponse:
    get:
      consumes:
      - application/json
      description: No description.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: No description.
swagger: "2.0"
