swagger: "2.0"
basePath: /fruit-basket
info:
  title: Fruit API
  version: 1.0.0
definitions:

  ObjectWithArrayProps:
    properties:
      payload:
        items:
          type: string
        type: array
    title: GetGoalsResponse
    type: object

  ObjectWithArrayPropsComplicate:
    properties:
      baselineReferenceNumber:
        type: string
      resultantId:
        type: string
      applications:
        type: array
        items:
          type: object
          properties:
            applicationId:
              type: string
            applicationNum:
              type: number
      otherObjArray:
        type: array
        items:
          $ref: '#/definitions/OtherObject'
  OtherObject:
    properties:
      Foo:
        type: string
paths: {}
